- name: "Creates directory"
  file:
    path: ~/web
    state: directory

- name: "Unarchive zipped backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/web

- name: "Install node dependencies"
  shell: |
    cd ~/web
    npm install

- name: "Executing node"
  shell: |
    cd ~/web/dist
    pm2 stop default
    # pm2 start npm -- start
    pm2 start main.js
  register: execute_node

- name: "print execute_node"
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu