- name: "wait 600 seconds for target connection to become reachable/usable."
  ansible.builtin.wait_for_connection:

- name: "Creates directory"
  file:
    path: ~/web
    state: directory

- name: "Copy the zipped artifact into the EC2 instance"
  template:
    src: "files/artifact.tar.gz"
    dest: "~/web/artifact.tar.gz"

- name: "Executing node"
  shell: |
    cd ~/web
    tar xvzf artifact.tar.gz
    pm2 stop default
    pm2 start npm -- start
